modLoader="javafml"
loaderVersion="[39,)" # Specify the minimum Forge version
license="MIT"
displayName="My Mod"
version="1.0.0"
description='''My Mod Description'''

[[dependencies]]
    modId="minecraft"
    mandatory=true
    version="[1.20.1,1.20.2)"

[[dependencies]]
    modId="forge"
    mandatory=true
    version="[39,)"
